version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4
      - image: postgres:9.5.1
        environment:
          POSTGRES_USER: root

    working_directory: ~/shikimori
    steps:
      - checkout
      # - run: apt-get update -qq && apt-get install -y build-essential nodejs
      - run: bundle install
      # - run: bundle exec rake db:create db:schema:load --trace
      # - run: bundle exec rake db:migrate
      # - run: bundle exec rspec
      - run: RAILS_ENV=test bundle exec rake db:create db:schema:load --trace
      - run: RAILS_ENV=test bundle exec rspec
