# config/chewy.yml
# separate environment configs
development: &development
  host: 'localhost:9200'
  prefix: 'shikimori_development'
test:
  <<: *development
  prefix: 'shikimori_test'
production:
  <<: *development
  host: 'localhost:9200'
  prefix: <%=ENV['USER'] != 'morr' ? 'shikimori_production' : 'shikimori_development' %>
