# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development: &defaults
  adapter: postgresql
  encoding: utf8
  database: shikimori_production
  username: shikimori_production
  host: localhost
  pool: 100
  timeout: 5000

production:
  <<: *defaults

test:
  <<: *defaults
  host: <%= ENV['PGHOST'] || 'localhost' %>
  database: <%= ENV['PGDATABASE'] || "shikimori_test_#{ENV['TEST_ENV_NUMBER']}" %>
  username: <%= ENV['PGUSER'] || 'shikimori_test' %>
