:anime:
  - 33209
  - 33446
  - 35614
  - 99999999
:manga:
  - 59267
:ranobe:
  - 88888888
:character:
  - 110319
  - 119407
  - 138658
  - 140981
  - 142087
  - 144815
  - 147901
  - 154599
  - 154600
  - 25685
  - 36063
  - 59077
  - 7746
  - 85731 # Bluegilly
  - 161947 # Shio Ihei
  - 137628 # Shousei Idera
  - 136780 # himawari
  - 158247 # Eclair Eclair Eicler
  - 99393 # Ouji Ryuuzaki
  - 156046 # Edward Mason
  - 144825 # Sakurai Motoki
:person:
  - 32789
  - 40128
